export const APP_CONSTANTS = {
  PAGINATION: {
    DEFAULT_PAGE: 1,
    DEFAULT_LIMIT: 20,
    MAX_LIMIT: 100,
  },
  CACHE_TTL: {
    PRODUCTS: 3600,
    CATEGORIES: 7200,
    SLOTS: 300,
    DEFAULT: 3600,
  },
  BUSINESS_HOURS: {
    START: 8,
    END: 18,
    SLOT_DURATION_MINUTES: 60,
  },
  ORDER_STATES: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    IN_PRODUCTION: "IN_PRODUCTION",
    READY_FOR_PICKUP: "READY_FOR_PICKUP",
    SHIPPING: "SHIPPING",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
  },
  APPOINTMENT_STATES: {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED",
    NO_SHOW: "NO_SHOW",
  },
}
